### ISSUE TITLE
Wrong answer sets for to example programs

### ISSUE THREAD

**Issue by tobiaskaminski** [AntoniusW/Alpha#19]
Alpha returns wrong answer sets for the following two programs.
```
node(a).
node(b).

in(X) :- not out(X), node(X).
out(X) :- not in(X), node(X).

pair(X,Y) :- in(X), in(Y).
```

The answer sets returned for the program are:
```
{ node(a), node(b), in(b), in(a), pair(b, b), pair(a, a), pair(b, a) }
{ out(a), node(a), node(b), in(b), pair(b, b) }
{ out(b), node(a), node(b), in(a), pair(a, a) }
{ out(b), out(a), node(a), node(b) }
```
The atom `pair(a,b)`is not derived by the last rule, only the inverse atom `pair(b,a)` is contained in the first answer set. The correct answer sets would be:
```
{ node(a), node(b), in(b), in(a), pair(b, b), pair(a, a), pair(b, a), pair(a, b) }
{ out(a), node(a), node(b), in(b), pair(b, b) }
{ out(b), node(a), node(b), in(a), pair(a, a) }
{ out(b), out(a), node(a), node(b) }
```

A variant of the first program where the error occurs due to a missing constraint is the following:
```
node(a).
node(b).

edge(b,a).

in(X) :- not out(X), node(X).
out(X) :- not in(X), node(X).

:- in(X), in(Y), edge(X,Y).
```
The answer sets returned for the program are:
```
{ edge(b, a), node(a), node(b), in(b), in(a) }
{ out(a), edge(b, a), node(a), node(b), in(b) }
{ out(b), edge(b, a), node(a), node(b), in(a) }
{ out(b), out(a), edge(b, a), node(a), node(b) }
```
The first answer set should be removed by the constraint. The correct answer sets would be:
```
{ out(a), edge(b, a), node(a), node(b), in(b) }
{ out(b), edge(b, a), node(a), node(b), in(a) }
{ out(b), out(a), edge(b, a), node(a), node(b) }
```

**Comment by AntoniusW** [comment]
The above ASP programs are now test cases and the underlying issues are fixed. If you find any further programs where Alpha yields wrong results, please open new issues.
