### ISSUE TITLE
Empty set wrongly computed as answer set (for rules with more than one default negation in the body)

### ISSUE THREAD

**Issue by gschenner** [AntoniusW/Alpha#3]
Hi,
For 

```
a:-not b,not c.
b:-not a,not c.
```

Alpha currently returns the expected answer sets {{a} {b}}.

For

```
a:-not b,not c.
b:-not a,not c.
c:-not a,not b.
```

the result also contains the empty answer set, which is not an valid answer set:

```
{ ChoiceOn(1), ChoiceOn(0), ChoiceOn(2), ChoiceOff(2), ChoiceOff(1), _R_(0, ), a() }
{ ChoiceOn(1), ChoiceOn(0), ChoiceOn(2), ChoiceOff(2), ChoiceOff(0), _R_(1, ), b() }
{ ChoiceOn(1), ChoiceOn(0), ChoiceOn(2), ChoiceOff(1), ChoiceOff(0), _R_(2, ), c() }
% wrong
{ ChoiceOn(1), ChoiceOn(0), ChoiceOn(2) }
```

KR Gottfried

**Comment by gschenner** [comment]
Hi,
I am not exactly sure, if filtering the empty answerset will fix the faulty behavior (but maybe i didn't understand [Refine predicate filtering #4](https://github.com/AntoniusW/Alpha/pull/4)  right):
In the case of the program below, Alpha currently will return the not empty answerset {somethingelse} as an answer set, which is wrong, because every answer set must contain either a, b, or c. I would have expected, that there is a problem in the solver.
```
somethingelse.
a:-not b,not c.
b:-not a,not c.
c:-not a,not b.
```

**Comment by AntoniusW** [comment]
Hi Gottfried,
the predicate filtering won't fix this issue. The issue at hand originates from a flaw in the algorithm. We locally have a fix for the algorithm, but uncovered another bug that also needs to be fixed before the above program yields correct results. We are working on the latter bug and commit the full fix then.

Best,
Antonius

**Comment by AntoniusW** [comment]
Hi,
the recent commit 022c90a on master should fix the solving algorithm. The above programs should yield the correct answer-sets now. Please confirm and/or report any further failing programs. Thank you!

Best,
Antonius

**Comment by AntoniusW** [comment]
Thank you again! With commit dbb4356 the underlying bug exhibited by your latest program is fixed. It also includes a performance boost since the grounder now avoids some unnecessary re-computations.

I was, however, not able to confirm your observation that the default solver is slower than the naive solver. Could you provide more details, e.g., a program where it happens?

Best,
Antonius

**Comment by gschenner** [comment]
Hi,
With the new version everything works fine. Also the runtime problem of the default solver is fixed. In the previous version the default solver was slower for an pigeon hole encoding (5 pigeons).

KR Gottfried
