### ISSUE TITLE
Sort option not working

### ISSUE THREAD

**Issue by gschenner** [AntoniusW/Alpha#30]
The sort option is not working. Answer sets are always sorted. 
This seems to have 2 causes:

There is a bug in Line 205 of  [at/ac/tuwien/kr/alpha/Main.java](https://github.com/AntoniusW/Alpha/blob/master/src/main/java/at/ac/tuwien/kr/alpha/Main.java).
```if (options.hasOption(OPT_SORT)) {```
should be:
``` if (commandLine.hasOption(OPT_SORT)) {```

And both the solver and the sort option use -s, therefore if the solver option is present the sort option is also set.

**Comment by AntoniusW** [comment]
Fixed both causes in ad7170e, sorting answers sets now works with -sort.
