### ISSUE TITLE
ArrayIndexOutOfBoundsException when trying to solve Hanoi Tower

### ISSUE THREAD

**Issue by rtaupe** [AntoniusW/Alpha#36]
In d1e9b64c7cae1a37a54de889cb49a18223d4f80b, test cases for four different instances of the [Tower of Hanoi problem](https://www.mat.unical.it/aspcomp2013/HanoiTower) are added to the project.
By this, a bug can be discovered that causes an ArrayIndexOutOfBoundsException to be thrown by `at.ac.tuwien.kr.alpha.common.NoGood.getLiteral(int)`:

> java.lang.ArrayIndexOutOfBoundsException: -1
> 	at at.ac.tuwien.kr.alpha.common.NoGood.getLiteral(NoGood.java:100)
> 	at at.ac.tuwien.kr.alpha.solver.WatchedNoGood.getLiteralAtAlpha(WatchedNoGood.java:68)
> 	at at.ac.tuwien.kr.alpha.solver.BasicNoGoodStore.addAlphaWatch(BasicNoGoodStore.java:102)
> 	at at.ac.tuwien.kr.alpha.solver.BasicNoGoodStore.ensureWatchInvariantAfterAssignAtLowerDL(BasicNoGoodStore.java:575)
> 	at at.ac.tuwien.kr.alpha.solver.BasicNoGoodStore.propagate(BasicNoGoodStore.java:635)
> 	at at.ac.tuwien.kr.alpha.solver.DefaultSolver.tryAdvance(DefaultSolver.java:104)
> 	at at.ac.tuwien.kr.alpha.solver.AbstractSolver$1.tryAdvance(AbstractSolver.java:31)

This was observed in the following constellations:
* `HanoiTowerTest.testInstance2()` with `random BerkMinLiteral`
* `HanoiTowerTest.testInstance1()` with `random Naive`

**Comment by AntoniusW** [comment]
I am not able to replicate the bug (neither `random Naive` nor `random BerkMinLiteral`) after merging fbc723b locally into testing-hanoi. Do you perhaps know the random seeds that caused the exceptions?
Could you verify whether the bug is still present?

**Comment by rtaupe** [comment]
Cannot reproduce this either, so possibly it has been fixed by fbc723b58d73386d8deae9da66d8bdb1c6f6344f.
