### ISSUE TITLE
False negatives by ChoiceManager#isAtomChoice

### ISSUE THREAD

**Issue by rtaupe** [AntoniusW/Alpha#39]
As demonstrated by at.ac.tuwien.kr.alpha.solver.ChoiceManagerTests.testIsAtomChoice() in 27bb7856b9ecbe2827d62109b6d1dd2fb786a1d7, ChoiceManager.isAtomChoice(int) returns false in cases where it should return true (at least to my understanding).

**Comment by AntoniusW** [comment]
The test did only call grounder.getNoGoods after adding the choice information to the ChoiceManager, but the Grounder computes the choice information only during getNoGoods. Calling getNoGoods first fixes the test case (done and merged in bc492bc ).
