### ISSUE TITLE
Number of answer set depends on order of literals in constraint

### ISSUE THREAD

**Issue by gschenner** [AntoniusW/Alpha#5]
Hi,
In the following program the number of answer sets produced by the solver depend on the order of the literals in the constraint. Without a constraint the correct answer sets are found i.e. 27 - 3 variables that can have 3 different values. With the constraint all the values of the variables should be different and therefore 6 answer set should remain. The correct result is neither found by the naive nor by the default solver. If the order of literals in the constraint is changed, the number of resulting answer sets change.
```
eq(1,1).
eq(2,2).
eq(3,3).
var(1).
var(2).
var(3).
val(VAR,1):-var(VAR),not val(VAR,2),not val(VAR,3).
val(VAR,2):-var(VAR),not val(VAR,1),not val(VAR,3).
val(VAR,3):-var(VAR),not val(VAR,1),not val(VAR,2).

% 0 answer sets
%:- val(VAR1,VAL1), val(VAR2,VAL2), eq(VAL1,VAL2), not eq(VAR1,VAR2).
% different literal order: 27 answer sets
%:- eq(VAL1,VAL2), not eq(VAR1,VAR2), val(VAR1,VAL1), val(VAR2,VAL2).
```
KR Gottfried

**Comment by gschenner** [comment]
The bug isn't specific to the constraint or default negation:
The following program derives the _something_ although _anything_ should be false (Parameters were -g naive -s naive/default). Hope this helps.
```
val(1,1).
val(2,2).
something:- val(VAR1,VAL1), val(VAR2,VAL2), anything(VAL1,VAL2).
% result: { val(1, 1), val(2, 2), something() }
```

**Comment by AntoniusW** [comment]
After another bug in the grounder was fixed, it seems that the above programs work correctly now for the recent commits in master.

Best,
Antonius

**Comment by flowlo** [comment]
Closing this for now. Feel free to re-open or comment here in case of regression. :)
