### ISSUE TITLE
implied atom not in answer set

### ISSUE THREAD

**Issue by gschenner** [AntoniusW/Alpha#6]
Hi,
Something i stumbled across, when i was porting a GGP [tic tac toe](http://alloyggp.blogspot.co.at/2014/04/the-annotated-tic-tac-toe.html) program to ASP. The following program should have one answer set containing tictactoe(b,...). Alpha returns one answer set but without the atom tictactoe(b,...).

```
next(1,2).
size(1).
size(2).
size(3).
cell(R,C,b,1) :- size(R), size(C).

cell(M,N,b,TNEXT):-
    next(T,TNEXT),
    cell(M,N,b,T),
    not isMarked(M,N,T).

tictactoe(M11,M12,M13,M21,M22,M23,M31,M32,M33):-
    cell(1,1,M11,2),
    cell(1,2,M12,2),
    cell(1,3,M13,2),
    cell(2,1,M21,2),
    cell(2,2,M22,2),
    cell(2,3,M23,2),
    cell(3,1,M31,2),
    cell(3,2,M32,2),
    cell(3,3,M33,2).

% answer set should contain tictactoe(b,b,b,b,b,b,b,b,b)
```

KR Gottfried

**Comment by gschenner** [comment]
Maybe this helps. A smaller example for the same strange behavior.
```
next(1,2).
cell(1,1,0,1).
cell(1,2,0,1).

cell(M,N,0,TNEXT):-
    next(T,TNEXT),
    cell(M,N,0,T),
    not isMarked(M,N,T).

withoutvar:-
    cell(1,1,0,2),
    cell(1,2,0,2).
     
withvar(X,Y):-
    cell(1,1,X,2),
    cell(1,2,Y,2).
% withvar is not in the answer set
%{ cell(1, 2, 0, 2), cell(1, 1, 0, 1), cell(1, 2, 0, 1), cell(1, 1, 0, 2), next(1, 2), withoutvar() }
```

**Comment by AntoniusW** [comment]
With current master, both programs contain the previously-missing atoms now. I think the issue is gone, although I am not sure which of the many bugfixes is responsible. If you encounter further bugs, please open an issue again. Thanks!
